// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgsQGu6lfwB4CplbF0swMppBkmVvLZZEs',
    appId: '1:816364706362:web:28cb70e2bdb7e0654e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    authDomain: 'onboarding-x-app-tnb.firebaseapp.com',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
    measurementId: 'G-Y83JPF698Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo9WmZ3UmbUPNB95lqxOP-UaV440Z4uco',
    appId: '1:816364706362:android:2ae915df46da685f4e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfCEJSelludyF9eOdmioCfOPAPQC0_RD0',
    appId: '1:816364706362:ios:59130dea86e0c55a4e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
    iosClientId: '816364706362-jiur90v89o5c0je2r5en6hoqnc82tv8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfCEJSelludyF9eOdmioCfOPAPQC0_RD0',
    appId: '1:816364706362:ios:59130dea86e0c55a4e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
    iosClientId: '816364706362-jiur90v89o5c0je2r5en6hoqnc82tv8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgsQGu6lfwB4CplbF0swMppBkmVvLZZEs',
    appId: '1:816364706362:web:1ef5a8840c1df72e4e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    authDomain: 'onboarding-x-app-tnb.firebaseapp.com',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
    measurementId: 'G-NZK6N1BGJB',
  );
}
